theme: jekyll-theme-minimal
title: Tech Truth Serum
description: On Tech Truth Serum, candid thoughts and lessons learned over the years are shared. The mission is to cut through the hype in tech. The goal is to maintain simplicity.
